Documents/mypythonproject/mysite/mysite/blog/urls.py
from django.urls import path
from .views import *
app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('recommendations/', post_recommendation, name='post_recommendations'),
]

Documents/mypythonproject/mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

Documents/mypythonproject/mysite/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from taggit.models import Tag
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class FavouriteTags(models.Model):
    tag_name = models.ForeignKey(Tag, related_name='like_tag', on_delete=models.CASCADE)

class SavedPosts(models.Model):
    post = models.ForeignKey(Post, related_name='saved', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='saved', on_delete=models.CASCADE)

Documents/mypythonproject/mysite/mysite/blog/forms.py
from django import forms
from .models import *


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SavedForm(forms.ModelForm):
    class Meta:
        model = SavedPosts
        fields = ('post',)

Documents/mypythonproject/mysite/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, FavouriteTags
from .forms import *
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.models import User

USER = User.objects.get(username='admin')

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    context = {
        'page': page,
        'posts': posts,
        'tag': tag,
    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm()
    save_form = SavedForm()
    if request.method == 'POST':
        if 'comment' in request.POST:
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.save()

        if 'save' in request.POST:
            try:
                save_data = SavedPosts.objects.get(post=post, user=USER)
            except:
                create_data = SavedPosts.objects.create(post=post, user=USER)
                create_data.save()
                print('ulala')
            else:
                save_data.delete()
                print('no')
    else:
        comment_form = CommentForm()
        save_form = SavedForm()

    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'save_form': save_form,
    }
    return render(request,
                  'blog/post/detail.html', context)


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            sent = True
    else:
        form = EmailPostForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context)


def post_recommendation(request):
    tags_list = []
    tags = FavouriteTags.objects.all()

    for tag in tags:
        tags_list.append(tag.tag_name.id)
    print(tags_list)
    recommended_posts = Post.published.filter(tags__in=tags_list)
    recommended_posts = recommended_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')
    paginator = Paginator(recommended_posts, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,

    }
    return render(request, 'blog/post/recommendation.html', context)

Documents/mypythonproject/mysite/mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
      <p>This is my blog.</p>
  </div>
</body>
</html>

Documents/mypythonproject/mysite/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
   {% if post.tags.all %}
        <p class="tags">
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug%}">{{tag.name}}</a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
   {% endif %}
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
<hr>
  <p>
    <a href="{% url 'blog:post_share' post.id %}">
      Share this post
    </a>
  </p>
  <form method="post">
        {% csrf_token %}
        <input class="save_button" type="submit" value="saved" name="save">
  </form>
   {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
    {% else %}
      <h2>Add a new comment</h2>
      <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment" name="comment"></p>
      </form>
    {% endif %}
{% endblock %}

Documents/mypythonproject/mysite/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2> Posts tagged with {{ tag.name }}</h2>
  {% endif %}
  {% for post in posts %}
    <div>
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
     {% if post.tags.all %}
        <p class="tags">
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug%}">{{tag.name}}</a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
     {% endif %}

    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    </div>
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

Documents/mypythonproject/mysite/mysite/blog/templates/blog/post/recommendation.html
{% extends "blog/base.html" %}

{% block title %}Recommendations{% endblock %}

{% block content%}
   <h1>Recommendations</h1>
   {% for post in posts %}
    <div>
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
     {% if post.tags.all %}
        <p class="tags">
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug%}">{{tag.name}}</a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
     {% endif %}

    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    </div>
  {% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

Documents/mypythonproject/mysite/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

Documents/mypythonproject/mysite/mysite/blog/templates/blog/post/test.html
<form  method="post">
      {% csrf_token %}
      <input type="submit" value="saved" name="save">
</form>
{{ val }}

Documents/mypythonproject/mysite/mysite/blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>